# Generated by Django 4.2 on 2023-04-10 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('detail', models.TextField(verbose_name='Описане')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('detail', models.TextField(verbose_name='Описане')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Отзыв на пользователя',
                'verbose_name_plural': 'Отзывы на пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': ()},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Заказчик'), (1, 'Специалист')], default=0, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.media')),
                ('file', models.ImageField(upload_to='orders/photos/', verbose_name='Фото')),
            ],
            bases=('board.media',),
        ),
        migrations.CreateModel(
            name='OrderVideo',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.media')),
                ('file', models.FileField(upload_to='orders/videos/', verbose_name='Видео')),
            ],
            bases=('board.media',),
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.AddField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.orderstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='ordervideo',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderphoto',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.order', verbose_name='Заказ'),
        ),
    ]
